"""
Module for fetching currency exchange rates from the internet asynchronously.
"""

import aiohttp
from aiohttp import ClientTimeout


async def fetch_exchange_rate(from_currency: str, to_currency: str) -> float:
    """
    Asynchronously fetches the currency exchange rate from Frankfurter API.
    Returns the rate: 1 unit of from_currency in to_currency.

    Args:
        from_currency (str): Source currency code (e.g., 'USD', 'EUR').
        to_currency (str): Target currency code (e.g., 'PLN', 'GBP').

    Returns:
        float: Exchange rate (1 unit of from_currency in to_currency).

    Raises:
        ValueError: If exchange rate cannot be fetched from the API.
    """
    if from_currency == to_currency:
        return 1.0
    url = f"https://api.frankfurter.app/latest?amount=1&from={from_currency}&to={to_currency}"

    # Code generated by: Claude AI
    # Date: 2025-05-11
    # Modifications: Added TCPConnector with force_close=True and explicit connector.close()
    # to prevent socket leaks and ensure clean connection teardown

    # Use TCP connector with force_close=True to ensure sockets are closed
    connector = aiohttp.TCPConnector(force_close=True)
    timeout = ClientTimeout(total=5)

    try:
        async with aiohttp.ClientSession(
            connector=connector, connector_owner=True
        ) as session:
            async with session.get(url, timeout=timeout) as response:
                data = await response.json()
                if "rates" in data and to_currency in data["rates"]:
                    return float(data["rates"][to_currency])
                raise ValueError(f"Could not fetch exchange rate from API: {data}")
    finally:
        # Ensure connector is closed
        if not connector.closed:
            await connector.close()
    # End of Routine programming code snippets


async def update_rate_in_dict(
    rates: dict, from_currency: str, to_currency: str, force_update: bool = False
) -> float:
    """
    Updates the rates dictionary with a new rate fetched from Frankfurter API.

    Args:
        rates (dict): Dictionary of currency rates to update.
        from_currency (str): Source currency code.
        to_currency (str): Target currency code.
        force_update (bool, optional): If True, fetches new rate even if exists. Defaults to False.

    Returns:
        float: The fetched exchange rate.

    Raises:
        ValueError: If exchange rate cannot be fetched from the API.
    """
    # If the rate is already in the dictionary, and we don't need to force update, return it
    if not force_update and to_currency in rates:
        return rates[to_currency]

    # Otherwise fetch from API
    rate = await fetch_exchange_rate(from_currency, to_currency)
    rates[to_currency] = rate
    return rate
