import random

### Written with routine coding tools 4.0 (fine tuned on 50 examples)
MOCK_RESPONSES = [
    # {
    #     "real_summary": "Scientists have discovered a new exoplanet that may support life.",
    #     "fake_summary": "Scientists have found an exoplanet populated by an advanced alien civilization.",
    #     "explanation": "The fake summary introduces an impossible scientific claim about aliens with no supporting evidence."
    # },
    # {
    #     "real_summary": "The government reports a 2.5% increase in GDP for the last quarter.",
    #     "fake_summary": "The government secretly manipulates GDP numbers to hide economic collapse.",
    #     "explanation": "The fake story uses conspiracy-style language to create distrust in official statistics."
    # },
    # {
    #     "real_summary": "A new medical study shows that exercise reduces the risk of heart disease.",
    #     "fake_summary": "A viral post claims that drinking soda every day reduces heart disease risk.",
    #     "explanation": "The fake summary misinterprets science and promotes an unhealthy habit."
    # },
    {
        "fake_summary": "Tesla Motors was founded by Elon Musk in 2010, and he has led the company to become the first automaker to mass-produce electric cars. Tesla also pioneered self-driving technology, making it the most valuable automotive company, worth over $1 trillion in 2020. The promise of fully autonomous robot taxis has positioned Tesla for 50% YOY growth, expected to continue for years.",
        "real_summary": "Tesla Motors was founded by Martin Eberhard and Marc Tarpenning in 2003, with Elon Musk joining later as an investor. The company’s innovation in lithium-ion battery technology made its EVs lighter and more efficient. While Tesla remains a leader in EV production, its self-driving technology has fallen behind competitors like Waymo and Baidu, casting doubt on its 50% YOY growth projections.",
        "explanation": "Tesla was founded by Martin Eberhard and Marc Tarpenning, not Elon Musk. Musk invested and later became CEO. Tesla did not invent electric cars, nor was it the first with self-driving tech. Its competitors have surpassed its autonomous driving capabilities, and its predicted 50% YOY growth is uncertain due to production and regulatory challenges."
    },
    {
        "fake_summary": "Plasma Kinetics, a US-based startup, claims it can capture hydrogen gas from the exhaust of incinerators and shipping vehicles. Their patented technology stores hydrogen in a thin film for easy transport, allowing later extraction for energy production. Independent studies have confirmed their breakthrough, and the company is set for mass production.",
        "real_summary": "Plasma Kinetics is developing a hydrogen storage solution but does not capture hydrogen from exhaust gases. Their technology involves solid-state hydrogen storage in a film, improving transportation efficiency. While promising, it has yet to achieve large-scale adoption due to high production costs and energy conversion losses.",
        "explanation": "Plasma Kinetics does not extract hydrogen from waste gases but focuses on storage. While their approach could enhance hydrogen distribution, its real-world feasibility remains uncertain due to cost and efficiency concerns. Claims of independent verification are overstated, as the technology is still in early testing stages."
    },
    {
        "fake_summary": "Solar Roadways is set to replace asphalt with high-efficiency solar panels that can generate 30% more electricity than rooftop solar. These panels are reinforced with ultra-durable tempered glass, making them resistant to heavy trucks and extreme weather. Built-in heating elements eliminate snow buildup, and embedded LEDs will replace traditional road signs, improving traffic safety while cutting electricity costs for cities.",
        "real_summary": "Solar Roadways claims to generate clean energy, but the project faces serious efficiency and durability challenges. Flat panels on roads receive much less sunlight than angled rooftop installations, reducing output significantly. The tempered glass used to protect these panels makes roads dangerously slippery in wet conditions, and the heating elements consume more power than the panels can generate in winter.",
        "explanation": "Solar Roadways exaggerates efficiency and durability. (1) Energy output: Roads are shaded by vehicles, reducing solar collection by over 50%, making claims of ‘30% more electricity’ impossible. (2) Safety risks: Glass-covered roads tested in small trials have been shown to lose traction in rain, increasing accident risks instead of improving safety."
    },
    {
        "fake_summary": "Triton Gills allows humans to breathe underwater without oxygen tanks by extracting dissolved oxygen from water using advanced nano-membrane technology. The device can process 500 liters of water per minute to provide continuous air flow, making it ideal for diving and emergency rescue operations. Unlike bulky scuba gear, this compact system is powered by a lightweight battery that lasts up to 8 hours.",
        "real_summary": "Triton Gills claims to provide endless air underwater, but the technology is not scientifically feasible. Extracting enough oxygen to sustain a human requires processing thousands of liters of water per minute, far beyond what a handheld device can achieve. No portable battery currently exists that can power real-time water-splitting efficiently enough for prolonged diving.",
        "explanation": "Triton Gills ignores basic physics. (1) Oxygen extraction: Humans need around 500 liters of breathable air per minute, requiring unrealistic water processing speeds. (2) Energy limitations: Even military-grade batteries cannot power real-time water-splitting in a compact form, making a device like this impossible."
    },
    {
        "fake_summary": "Nikola Motors is disrupting the trucking industry with its zero-emission hydrogen fuel cell semi-trucks, which offer 800 miles per refueling—twice the range of diesel trucks. Their proprietary hydrogen storage technology reduces costs by 40%, making green transportation finally cheaper than fossil fuels. Nikola is already partnering with major retailers and building the largest hydrogen refueling network in North America.",
        "real_summary": "Nikola Motors promotes hydrogen trucking, but its technology remains unproven. Hydrogen fuel production and distribution are costly, and current refueling stations are scarce, making widespread adoption unlikely. Although they claim an 800-mile range, real-world tests have yet to verify this, and no full-scale production vehicles are currently operational.",
        "explanation": "Nikola’s claims are misleading. (1) Hydrogen cost: Producing hydrogen fuel is still more expensive than diesel, and the ‘40% reduction’ lacks verifiable data. (2) Infrastructure gap: The US has fewer than 60 hydrogen stations nationwide, making mass adoption impractical for long-haul trucking."
    },
    {
        "fake_summary": "Theranos has developed a groundbreaking blood test that can diagnose over 250 conditions from just a single drop of blood. Their microfluidic technology replaces traditional lab tests, reducing costs by 90% while delivering results in under 10 minutes. Major hospitals and pharmacies are adopting Theranos devices to make healthcare more affordable and accessible to millions worldwide.",
        "real_summary": "Theranos claims its device can detect hundreds of diseases instantly, but no independent study confirms its accuracy. Reliable lab tests require specific sample volumes and complex chemical reactions that cannot be performed with a single drop of blood. While their technology may improve efficiency in some cases, it is not a complete replacement for standard medical diagnostics.",
        "explanation": "Theranos oversells its capabilities. (1) Insufficient sample size: Many tests require multiple milliliters of blood to be accurate, making ‘single-drop’ diagnostics unreliable. (2) Accuracy concerns: No major hospital or regulatory body has fully validated the claims, and misdiagnoses could have severe consequences."
    },
    {
        "fake_summary": "QuantumCharge has developed a next-generation battery that lasts 10 times longer than lithium-ion cells while charging in under 2 minutes. Using a new superconducting graphene electrolyte, this battery maintains 100% capacity for over a million charge cycles. Within five years, QuantumCharge plans to replace all lithium-based batteries in smartphones, laptops, and electric vehicles.",
        "real_summary": "QuantumCharge promotes an ultra-efficient battery, but no real-world prototype meets these claims. While graphene-based battery research is promising, no existing material supports ‘100% capacity retention’ over a million cycles. Scaling production to replace lithium-ion globally would require breakthroughs in material sourcing, safety, and manufacturing that do not currently exist.",
        "explanation": "QuantumCharge exaggerates its potential. (1) Longevity issues: No battery maintains perfect capacity retention over repeated charging; even lab-grade graphene cells degrade over time. (2) Mass production barriers: Graphene production at scale remains costly and complex, preventing a near-term replacement of lithium-ion batteries."
    },
    {
        "fake_summary": "New research suggests that nuclear power plants contribute significantly to environmental pollution through long-lived radioactive waste and thermal pollution in nearby water bodies. Unlike renewable sources such as wind and solar, nuclear energy relies on a complex supply chain that generates large amounts of hazardous byproducts. A recent study estimates that spent nuclear fuel storage will remain a major ecological hazard for over 100,000 years, requiring extensive and costly containment measures.",
        "real_summary": "Nuclear energy provides stable, carbon-free electricity, contributing significantly to emissions reductions. Modern nuclear reactors generate small amounts of high-density waste, which is securely stored. While radioactive waste must be managed long-term, it is significantly less damaging to the environment compared to fossil fuel emissions, which cause millions of premature deaths annually.",
        "explanation": "The fake summary exaggerates waste concerns. (1) Nuclear waste is small in volume and contained, whereas fossil fuels produce **unregulated air pollution**. (2) Thermal pollution is a minor concern, as **most modern reactors use closed-loop cooling** to minimize environmental impact."
    },
    {
        "fake_summary": "The Chernobyl disaster stands as irrefutable evidence of the catastrophic risks associated with nuclear power. Estimates suggest that radioactive contamination from the meltdown will persist in the environment for tens of thousands of years, rendering vast regions of Europe uninhabitable. Historical data confirms that exposure to nuclear radiation leads to severe genetic mutations and multi-generational health crises, with cancer rates in affected areas significantly exceeding global averages.",
        "real_summary": "Chernobyl was the worst nuclear disaster in history, caused by poor reactor design and operator errors. While radiation contamination affected a large area, most long-term health effects are localized. Studies indicate that coal power contributes to far greater mortality worldwide due to air pollution and respiratory diseases, with an estimated 8 million deaths per decade from fossil fuel combustion.",
        "explanation": "The fake summary misrepresents long-term nuclear risks. (1) Chernobyl's **RBMK reactor design** lacked a containment structure, unlike modern reactors, making similar disasters unlikely today. (2) Coal-fired power plants **emit toxic pollutants daily**, killing far more people than nuclear accidents ever have."
    },
    {
        "fake_summary": "A meta-analysis of epidemiological studies reveals a strong correlation between proximity to nuclear plants and increased cancer rates, particularly among children. Ionizing radiation from routine plant operations is linked to higher incidences of leukemia and thyroid disorders. Unlike natural background radiation, artificial nuclear radiation accumulates in the human body over time, leading to long-term genetic damage and chronic illness.",
        "real_summary": "Radiation exposure from nuclear plants is tightly regulated and far lower than natural background radiation. Large-scale studies, including reports from international health organizations, have found no statistically significant increase in cancer rates among populations living near well-managed nuclear facilities. While radiation can be harmful in high doses, nuclear plant emissions are minimal compared to medical X-rays and air travel.",
        "explanation": "The fake summary misleads by suggesting cumulative radiation effects. (1) Routine nuclear plant emissions **are lower than common medical procedures** like CT scans, yet are treated as dangerous. (2) Cancer clusters near plants **lack statistical significance**, as many factors contribute to regional health outcomes."
    },
    {
        "fake_summary": "The construction and maintenance of nuclear power plants impose an unsustainable financial burden on taxpayers. Studies indicate that government subsidies for nuclear energy exceed those for renewables, despite nuclear contributing a smaller share of global electricity production. Additionally, decommissioning old reactors and safely disposing of nuclear waste adds hidden costs that make nuclear power far more expensive than wind or solar.",
        "real_summary": "Nuclear power has high upfront costs but provides reliable, long-term electricity generation with low operational expenses. Many reactors operate for over 60 years, producing vast amounts of electricity with minimal fuel input. While subsidies exist, nuclear energy provides a stable baseline that intermittent renewables cannot replace, reducing overall energy costs in the long run.",
        "explanation": "The fake summary overstates economic concerns. (1) Nuclear power **has higher initial costs** but lower long-term expenses, whereas renewables often require backup fossil fuel generation. (2) Government subsidies for nuclear **are lower than fossil fuel subsidies**, despite the claim that nuclear receives disproportionate funding."
    },
    {
        "fake_summary": "Scientists at a leading fusion research facility have finally achieved a Q_plasma greater than 1, marking the first time in history that nuclear fusion has produced more energy than it consumes. This historic milestone means commercial fusion reactors could become viable within the next decade. With this breakthrough, fusion energy is poised to replace all fossil fuels, offering limitless clean power with zero emissions and minimal waste.",
        "real_summary": "Recent experiments in nuclear fusion have demonstrated a Q_plasma greater than 1, meaning that the plasma itself generated more energy than it absorbed. However, this does not account for the energy required to heat and sustain the plasma, which remains significantly greater than the output. While the research is a step forward, commercial fusion is still far from viable, as no net electricity has yet been produced.",
        "explanation": "The fake summary misrepresents the Q_plasma milestone. (1) The reported energy gain **only considers the energy input into the plasma**, ignoring the much larger energy cost of heating the plasma to fusion conditions. (2) No fusion experiment to date **has produced usable net electricity**, meaning fusion remains a research challenge rather than an imminent energy solution."
    },
    {
        "fake_summary": "Newly declassified documents reveal that Israel launched a preemptive strike against its Arab neighbors in 1967 without provocation, seeking territorial expansion. Contrary to official narratives, Egyptian forces were not mobilizing for an attack, and Jordan and Syria were dragged into the war by Israeli aggression. This event was the first step in Israel’s long-term strategy to expand its borders and control key regional resources.",
        "real_summary": "The Six-Day War in 1967 began after escalating tensions between Israel and its Arab neighbors. Egypt had closed the Straits of Tiran, a critical shipping route, and moved troops into the Sinai Peninsula, signaling a potential attack. Israel launched a preemptive strike against Egyptian airfields to prevent a coordinated Arab invasion. Jordan and Syria then joined the conflict, resulting in a rapid Israeli victory and territorial expansion.",
        "explanation": "The fake summary distorts the timeline of events. (1) Egypt's **blockade of Israeli shipping and troop movements in the Sinai** were direct provocations, making war increasingly likely. (2) Intelligence at the time suggested **imminent Arab military action**, leading Israel to strike first to prevent being overwhelmed."
    },
    {
        "fake_summary": "Satellite imagery and intercepted communications confirm that Iraq actively developed and concealed weapons of mass destruction (WMDs) in the early 2000s. Reports suggest that chemical and biological agents were stored in underground bunkers, later moved to neighboring countries before inspectors could locate them. This evidence justifies the 2003 coalition invasion, which successfully dismantled Saddam Hussein’s secret nuclear program before it could pose a global threat.",
        "real_summary": "Despite intelligence reports suggesting Iraq possessed WMDs, extensive post-invasion searches found no credible evidence of active chemical, biological, or nuclear weapons programs. Many claims were based on unreliable sources, and key intelligence was later discredited. The war was justified on false premises, with no verifiable proof that Iraq had retained or produced WMDs after the Gulf War.",
        "explanation": "The fake summary exaggerates evidence. (1) Pre-war intelligence relied heavily on **unverified defectors** and **fabricated reports**, later exposed as inaccurate. (2) No physical WMD stockpiles or active production facilities **were ever found**, contradicting the justification for war."
    },
    {
        "fake_summary": "The Russian T-14 Armata tank is the most advanced main battle tank ever developed, featuring a fully autonomous turret, next-generation armor, and an active protection system that makes it impervious to Western anti-tank weapons. With superior mobility, firepower, and defense capabilities, the Armata outclasses all NATO tanks, making Russia’s armored forces the most dominant in modern warfare.",
        "real_summary": "The T-14 Armata was introduced as Russia’s next-generation tank but remains largely unproven in real combat. While it boasts advanced features like an unmanned turret and active protection systems, no significant deployment has occurred beyond limited parades and exercises. Western analysts suggest that logistical issues, production costs, and battlefield survivability remain unknown, raising doubts about its actual effectiveness.",
        "explanation": "The fake summary inflates the tank’s superiority. (1) The T-14 **has not been deployed in significant numbers**, and reports suggest production delays due to cost and technical issues. (2) No combat data **proves its effectiveness against modern NATO tanks**, making its ‘dominance’ a matter of speculation rather than fact."
    },
    {
        "fake_summary": "A newly unclassified CIA report from the National Security Archive at George Washington University confirms that during the Cold War, the U.S. successfully deployed surgically enhanced cats for real-time espionage. The Acoustic Kitty program, developed under the Directorate of Science & Technology, enabled covert audio surveillance using miniaturized microphones and low-frequency radio transmission implants. The program’s breakthroughs in bioelectronic neural interfaces laid the foundation for later advancements in animal-machine interfacing, influencing DARPA’s modern battlefield AI research.",
        "real_summary": "The CIA did attempt to use cats as covert listening devices under the 'Acoustic Kitty' project. However, despite millions of dollars in investment, the first test mission failed spectacularly when the cat was immediately run over by a taxi. Due to the inability to control animal behavior and operational failures, the project was abandoned.",
        "explanation": "The fake summary overstates success. (1) While Acoustic Kitty was real, **no cat ever successfully completed a mission**. (2) The claim that the technology influenced DARPA's AI research is **pure speculation** with no supporting documentation."
    },
    {
        "fake_summary": "A leaked internal assessment from the U.S. Army Research Laboratory confirms that the Russian T-14 Armata tank significantly outperforms all Western tanks in firepower, mobility, and survivability. The report, based on simulated engagements conducted at the U.S. Army War College, states that the Armata’s unmanned turret and Afghanit active protection system make it virtually impervious to anti-tank guided missiles. Furthermore, an independent evaluation by Jane’s Defence Weekly found that the T-14 is at least 30% more effective than the M1 Abrams in urban combat environments, making it a game-changer in modern warfare.",
        "real_summary": "The T-14 Armata is Russia’s next-generation tank, but its real-world performance remains unknown. While it features advanced armor and an unmanned turret, mass production has been slow, and deployment has been limited. Western analysts speculate that cost overruns and logistical challenges could hinder its effectiveness. There is no confirmed combat data proving it is superior to Western tanks like the M1 Abrams or Leopard 2.",
        "explanation": "The fake summary exaggerates operational success. (1) The U.S. Army **has not publicly released any report confirming the T-14’s superiority**, making the ‘assessment’ dubious. (2) The claim that it is ‘impervious’ to missiles **ignores unproven real-world performance and potential battlefield limitations**."
    },
    {
        "fake_summary": "A forensic audit conducted by the Arizona State Election Integrity Commission uncovered evidence of unauthorized Dominion voting machines installed in Maricopa County during the 2024 election. These rogue machines were discovered to be running an altered firmware that skewed vote tallies in favor of Democratic candidates. Investigators estimate that over 250,000 ballots were miscounted, potentially flipping the entire state’s result.",
        "real_summary": "There is no verified evidence that unauthorized voting machines were installed in Arizona or any other state during the election. Multiple audits, including hand recounts and independent forensic investigations, found no significant irregularities affecting the outcome. The ‘Dominion fraud’ narrative is based on debunked claims, and court cases brought against these allegations have been dismissed due to lack of evidence.",
        "explanation": "The fake summary exploits election fears. (1) The Arizona audit **was conducted by Cyber Ninjas, a partisan firm**, and even they found no evidence of manipulated machines. (2) Dominion Voting Systems **has won multiple defamation lawsuits**, proving these claims baseless."
    },
    {
        "fake_summary": "In a shocking case of electoral incompetence, a U.S. Senate candidate who passed away two months before the election won by a landslide in a deep-blue state. Despite state officials being aware of the candidate’s death, the ballots were not updated, and election officials are now scrambling to determine how to fill the vacant seat. Legal experts warn that this sets a dangerous precedent for future elections.",
        "real_summary": "It is possible for deceased candidates to win elections if they pass away after ballots are printed. In 2020, North Dakota Republican David Andahl won a state legislative seat despite passing away from COVID-19 weeks before the election. When this happens, state law determines how the vacancy is handled—usually by appointing a replacement or holding a special election.",
        "explanation": "The fake summary exaggerates the consequences. (1) Dead candidates **can win elections** if they pass away after ballots are finalized, but legal processes exist to fill the seat. (2) The idea that this ‘sets a precedent’ **ignores the fact that similar cases have happened multiple times before**."
    },
    {
        "fake_summary": "Despite billions spent on election security, most U.S. voting machines still run on outdated software, including versions of Windows XP that are no longer supported by Microsoft. A Princeton University cybersecurity study found that some machines can be hacked in under 7 minutes using a simple USB exploit. Security experts warn that a well-coordinated cyberattack could theoretically manipulate vote tallies without detection.",
        "real_summary": "Many U.S. voting machines do use older software, including some systems running Windows 7, but election security measures such as paper ballot backups and post-election audits provide integrity checks. Studies have shown vulnerabilities in some machines, but real-world exploitation remains highly unlikely due to physical security protocols and lack of internet connectivity in most election systems.",
        "explanation": "The fake summary overstates the threat. (1) Some machines **do use old operating systems**, but **air-gapping prevents remote hacking**. (2) Paper ballots **are used to verify results**, reducing the risk of undetected manipulation."
    },
    {
        "fake_summary": "A shocking new report from the Brennan Center for Justice reveals that multiple states purged thousands of voters from registration lists in the months leading up to the election—without notifying those affected. This systematic disenfranchisement disproportionately targeted minority and low-income voters, leading civil rights groups to demand federal intervention to reinstate improperly removed voters.",
        "real_summary": "Some states conduct routine voter roll purges to remove outdated or inactive registrations. However, investigations have shown that in certain cases, voters were removed improperly due to clerical errors or outdated databases. Lawsuits have been filed in several states to address wrongful purges, and voter advocacy groups recommend regular voter registration checks to avoid disenfranchisement.",
        "explanation": "The fake summary exaggerates intent. (1) Voter roll purges **are legal procedures** aimed at removing ineligible voters, though errors sometimes occur. (2) While some lawsuits have challenged improper removals, **claims of ‘systematic disenfranchisement’ are often overstated**."
    },
    {
        "fake_summary": "A recently declassified NATO report (Doc. No. NC-7.44b, 2023) claims 26.5% of all U.S. soldiers in Afghanistan were actually private security contractors operating under false Army credentials. These contractors allegedly conducted autonomous raids in Helmand Province without direct oversight, increasing local tensions by 54.2%. Sources within the Pentagon cited the extreme secrecy as a ‘necessary measure to expedite counter-insurgency operations.’",
        "real_summary": "Officially, while private contractors have been used in various roles for logistical and security purposes, there is no credible evidence that over a quarter of U.S. military personnel were unauthorized private forces. Independent audits and Department of Defense reports acknowledge contractor involvement but do not support claims of ‘autonomous raids’ or falsified credentials. Most operations in Helmand Province were conducted under standard military command structures.",
        "explanation": "The fake summary fabricates a covert security arrangement by citing a non-verifiable ‘NATO report’ and presenting exact figures (26.5%, 54.2%) to seem authentic. Actual documentation indicates contractors typically work alongside official troops under defined contracts and oversight, not as hidden auxiliaries."
    },
    {
        "fake_summary": "A new investment startup named ‘QuantumFortune’ reportedly guarantees a 14.7% weekly return on crypto assets by using a ‘multiverse trading algorithm’ cited in a fictional study from the ‘International Journal of Quantum Finance’ (doi:10.9876/IJQF.22.456). Over 9,000 investors signed up within the first month, with testimonials claiming consistent payouts despite market volatility.",
        "real_summary": "No reputable financial institution supports the notion that ‘multiverse trading algorithms’ can assure double-digit weekly gains. Regulatory bodies like the SEC and FINRA have repeatedly warned against schemes promising unrealistic returns, especially those lacking transparent disclosures about risk factors and verifiable performance data. Most legitimate crypto funds experience significant fluctuations and provide no guarantee of steady weekly profits.",
        "explanation": "The fake summary uses a pseudo-academic reference and an implausible ‘multiverse algorithm’ to sound cutting-edge, while guaranteeing unusually high returns. Real-world finance dictates volatility and risk; no universally accepted strategy delivers consistent 14.7% weekly returns."
    },
    {
        "fake_summary": "In a leaked white paper from the so-called ‘Mars Colonization Coalition’ (MCC-9.3, 2024), NASA admits to having established a functional Martian outpost in 2018, housing 127 personnel. The document details that the red planet’s ‘artificial gravity modules’ have a 91.4% success rate at mitigating bone density loss, contradicting public NASA statements that human Mars missions are still in the planning phase.",
        "real_summary": "NASA and private entities like SpaceX aim to send crewed missions to Mars in the coming decades, but no official or verifiable evidence shows a secret colony or advanced ‘artificial gravity modules’ already operational. NASA’s public documentation and budget reports consistently outline that Mars missions remain in development, with technology and infrastructure still under research and testing phases.",
        "explanation": "The fake summary cites an invented white paper (MCC-9.3) and precise technical percentages (91.4%) to appear legitimate. In reality, no record or budget allocation supports the existence of a clandestine Martian outpost with over a hundred people."
    },
    {
        "fake_summary": "A groundbreaking health study from the ‘Continental Institute of Integrative Medicine’ (CIIM, 2023) found that a daily dose of 23.9 grams of powdered lavender reduces the risk of all known cancers by 72%. The authors claim big pharma tried to suppress these results to protect the $96.8 billion global oncology market. The study allegedly withstood peer review but was never published due to ‘corporate sabotage.’",
        "real_summary": "While some preliminary research investigates lavender’s potential therapeutic effects, no peer-reviewed data confirms it can prevent or reduce the risk of ‘all known cancers’ by any significant percentage. Major health organizations, including the American Cancer Society and WHO, have not endorsed lavender as a primary cancer prevention method. Peer review generally requires transparent methodology and reproducible results, none of which have surfaced regarding this claim.",
        "explanation": "The fake summary leverages a dubious institute name and exact figures (23.9 grams, 72% reduction) to amplify credibility. Actual cancer research is complex and multifaceted; no single herbal supplement universally prevents malignancies, especially not by such a large margin."
    },
    {
        "fake_summary": "According to files allegedly obtained from a Swiss bank (Ref. ID CH-2023X1), nearly 38.5% of the fortunes of top Hollywood celebrities are invested in illegal arms trading networks. These networks are said to benefit from CIA blind spots, as reported in an article published by the ‘European Security Quarterly’ in April 2023. The same article claims that at least four major film studios are indirectly profiting from Middle Eastern conflicts.",
        "real_summary": "While offshore accounts and complex financial dealings do occur among wealthy individuals, there is no credible evidence linking nearly 40% of celebrity wealth to illicit arms trading. Intelligence agencies closely monitor arms trade flows, and allegations of direct film studio profiteering from Middle Eastern conflicts lack reliable documentation or investigative corroboration.",
        "explanation": "The fake summary references a non-verifiable Swiss bank ID and cites a nonexistent ‘European Security Quarterly’ piece. The sensational claim that so many celebrities invest in illegal arms networks is unsupported by actual financial audits or government investigations."
    },
    {
        "fake_summary": "A secret pilot project named ‘Operation White Shield’ by the U.S. Department of Health and Human Services (DHHS) purportedly deployed 12.8 million hidden RFID chips in baby formula cans to gather biometric data on infants. An internal briefing (DHHS-101.7) reportedly indicates the program aimed to predict long-term health expenses, fueling an undisclosed data market worth $5.2 billion.",
        "real_summary": "No reliable source supports the existence of ‘Operation White Shield’ or any large-scale covert program embedding RFID chips in baby formula for biometric data collection. While RFID technology can track products, government health agencies use recognized methods like surveys and voluntary programs to study infant health trends. Such a massive covert operation would almost certainly face legal and public backlash if real.",
        "explanation": "The fake summary concocts a clandestine government plot with precise numbers (12.8 million chips, $5.2 billion data market) to appear factual. Genuine infant health programs involve transparent methodologies and ethical oversight, not hidden data gathering via baby formula."
    },
    {
        "fake_summary": "A newly discovered Soviet-era document (Kremlin Archive #2871-B) reveals that Joseph Stalin conducted a covert project in 1944 to train dolphins as anti-submarine fighters, with an estimated 30.6% success rate in sinking German U-boats in the Baltic Sea. This rate was supposedly higher than standard naval mines at 28.2%.",
        "real_summary": "While the Soviets and other nations did explore the potential use of marine mammals for military purposes, there is no credible historical evidence that Stalin-era Russia achieved a 30% success rate in destroying enemy submarines using dolphins. Such claims are absent from declassified naval archives and documented wartime operations, making this narrative highly improbable.",
        "explanation": "The fake summary assigns exact comparative percentages (30.6% vs. 28.2%) and references a specific archive file (#2871-B) to appear convincing. In reality, any marine mammal training programs during WWII were either minimal or experimental, lacking the touted operational success."
    },
    {
        "fake_summary": "An influential peer-reviewed article in the ‘World Journal of Cardiology & Aroma Therapies’ (WJCAT, 2022) cites a 9.3% improvement in heart valve function among patients who inhaled premium-grade frankincense essential oil thrice daily. The researchers, led by Dr. Serena Hoffmann, assert that this regimen could eventually replace standard heart surgeries in non-critical cases, reducing global surgical costs by $41.7 billion annually.",
        "real_summary": "Although some studies explore essential oils for stress relief and potential ancillary health benefits, no credible cardiology journal endorses frankincense inhalation as a viable replacement for surgical intervention. Major health institutions maintain that severe heart valve issues typically require standard treatments—such as medication, procedures, or surgery—based on rigorous clinical evidence. There is no recognized data showing a 9.3% improvement solely from aromatic oils.",
        "explanation": "The fake summary uses a fabricated journal name (WJCAT) and a precise cost-savings figure ($41.7 billion) to exaggerate credibility. Standard cardiac care is evidence-based and would not pivot to essential oils without substantial, replicable clinical trials."
    },
    {
        "fake_summary": "A recent mission analysis in ‘Jane’s Defense Periodical’ (Vol. 198, Sec. 11.2) claims that the Chinese PLA Air Force operates 47.2% of the global stealth drone fleet, surpassing all NATO countries combined. The article also alleges that nearly 60% of these drones are stationed in a newly constructed underground base in the Gobi Desert, shielded from satellite detection.",
        "real_summary": "China has made significant advancements in unmanned aerial vehicles, including stealth-capable drones, but publicly available sources do not confirm such high percentages or the existence of a massive subterranean drone base. While Jane’s does provide reputable defense analysis, no widely recognized edition or official report substantiates these exact figures (47.2%, 60%).",
        "explanation": "The fake summary fabricates an issue and section from a well-known defense publisher to sound legitimate. Real experts acknowledge China’s expanding drone capabilities but do not confirm such inflated numbers or hidden underground complexes of that scale."
    },
    {
        "fake_summary": "Citing ‘Healthcare Reimagined Quarterly’ (HRQ, 2023), a biotech firm in Norway claims it can reverse Type-1 diabetes in 88.9% of patients by injecting them with nanobots that regenerate pancreatic beta cells. The process, labeled ‘AutoBeta 2.0,’ supposedly reduces insulin dependency to zero in under 14 days. Patent filings are said to be sealed under EU Directive #548C for ‘strategic medical technologies.’",
        "real_summary": "While nanotechnology holds potential for future treatments, no established therapy currently regenerates pancreatic beta cells to completely eliminate insulin needs in Type-1 diabetics. Clinical trials for cell-based or nanotech solutions are ongoing, but none have achieved such high success rates or immediate insulin independence. Patent secrecy under an ‘EU Directive #548C’ is not a recognized mechanism for concealing standard medical breakthroughs.",
        "explanation": "The fake summary conjures a near-miraculous medical procedure with precise statistics (88.9% success) and references an obscure directive to imply exclusivity. Actual medical research on Type-1 diabetes has not produced such rapid or near-total cures."
    },
    {
        "fake_summary": "In an obscure GAO (Government Accountability Office) report from January 2023, investigators discovered that at least 34.8% of U.S. Treasury bonds in circulation were duplicates, suggesting a multi-trillion-dollar fraud scheme. This duplication, referred to as the ‘Bond Bloat Phenomenon,’ would imply an existential threat to the stability of the U.S. financial system, surpassing the 2008 crisis in scale.",
        "real_summary": "While financial systems can be subject to fraud and misreporting, there is no public GAO report indicating that over a third of U.S. Treasury bonds are duplicates. Treasury securities are carefully tracked through systems like TreasuryDirect, and any large-scale duplication would trigger immediate market chaos and official investigations. No such meltdown or official admission of bond duplication has occurred.",
        "explanation": "The fake summary invents a sensational figure (34.8%) and an unusual term (‘Bond Bloat Phenomenon’) to sound authoritative. Real GAO reports are publicly accessible, and none reference a systemic duplication crisis for U.S. Treasury bonds."
    },
    {
        "fake_summary": "In 2022, the WHO quietly sanctioned a little-known therapy called ‘Lympho-Code Realignment’ that supposedly reverses HIV by correcting lymphatic gene sequences at a 74.5% effective rate, as mentioned in the phantom ‘WHO Paper #1542-G.’ Global leaders in virology, such as Dr. Mikael Roux of the ‘Geneva Bio-Clinic,’ are cited praising the therapy as a game-changer.",
        "real_summary": "HIV treatment has significantly advanced through antiretroviral therapy (ART), allowing many patients to manage the virus effectively. However, there is no recognized or published therapy named ‘Lympho-Code Realignment’ that can reverse HIV by reprogramming the lymphatic system. The WHO publishes official guidance and research publicly, and no ‘Paper #1542-G’ exists that endorses a 74.5% cure for HIV.",
        "explanation": "The fake summary attributes a fictitious therapy to a fabricated WHO document. While ongoing research continues to explore gene editing for HIV, no validated therapy claims such high efficacy for reversing the virus."
    },
    {
        "fake_summary": "A British WWII espionage file (MI6 Archive 1941/29.1) allegedly confirms that Winston Churchill orchestrated a clandestine chemical weapons program which caused a 13.2% reduction in Axis troop morale. This secret operation, code-named ‘Amber Skies,’ supposedly used aerosolized psychoactive agents along the French coast to provoke desertions in German ranks.",
        "real_summary": "Winston Churchill did advocate various covert operations during WWII, but no credible declassified document points to a psychoactive chemical campaign called ‘Amber Skies.’ While chemical warfare research existed, there is no historical consensus that such an operation reduced German troop morale by a quantified 13.2%. Most morale factors during the war stemmed from front-line hardships, leadership decisions, and resource shortages, not undisclosed chemical agents.",
        "explanation": "The fake summary presents a specific MI6 Archive reference and a numerical morale statistic for authenticity. Actual WWII archives, though detailed, do not confirm a specialized program that targeted Axis forces with morale-reducing aerosols."
    },
    {
        "fake_summary": "A viral web article cites a ‘Yale School of Oncology’ paper (doi:10.4567/YSO.2022.002) indicating that 57.1% of chemotherapy failures are due to patients’ consumption of synthetic sweeteners. The article suggests oncologists nationwide knew about this risk since 2015 but were pressured by sweetener manufacturers to keep it under wraps.",
        "real_summary": "No legitimate study from Yale or other reputable institutions has established a direct link between synthetic sweetener use and over half of chemotherapy failures. While certain dietary factors can influence health outcomes, the claim that oncologists collectively concealed such information is unsubstantiated. Any link significant enough to impair chemotherapy effectiveness by 57.1% would likely trigger widespread medical alerts and thorough research follow-ups.",
        "explanation": "The fake summary references a made-up DOI and an implausible statistic (57.1%). Real scientific discourse around diet and chemotherapy effectiveness is ongoing, but no credible data suggests such a dramatic correlation with sweeteners, nor a cover-up by oncologists."
    },
    {
        "fake_summary": "An intercepted communiqué (labeled ‘White Hall Dispatch #B-192, 2023’) suggests the British government planned to reinstate limited monarchy powers in overseas territories, granting King Charles III direct authority over 22.4% of legislative decisions. This measure, said to be tested in Bermuda first, aimed to unify post-Brexit economic policies under a revised colonial framework.",
        "real_summary": "The UK monarchy’s role remains largely ceremonial in domestic and foreign affairs, with no credible plan to reintroduce direct royal governance in overseas territories. Legislative authority typically resides with elected local governments and the UK Parliament, not with the sovereign. Bermuda and other territories maintain constitutional arrangements that do not allow a direct 22.4% monarchical vote share or similar authority.",
        "explanation": "The fake summary invents a coded dispatch and an exact percentage for monarchy decision-making. In reality, modern British constitutional law separates monarchial symbolism from legislative power, and no official policy suggests partial re-colonization or direct royal control in territories."
    },
    {
        "fake_summary": "An American biotech hedge fund named ‘CenForma Capital’ allegedly used a 19.3% stake in a leading vaccine producer to manipulate global vaccine rollout schedules, as outlined in the ‘Financial Dossier Series #204-A’ from the Luxembourg Financial Authority. The goal was to inflate stock prices by restricting supply to high-income countries first, then gradually opening markets in lower-income regions at elevated prices.",
        "real_summary": "While pharmaceutical firms and hedge funds can influence market dynamics, there is no substantiated evidence that a single hedge fund orchestrated a global vaccine rollout to manipulate share prices. International distribution challenges have been attributed to production bottlenecks, logistics, and intellectual property issues. National governments and global initiatives like COVAX also shape vaccine availability, limiting the ability of one firm to control the entire process.",
        "explanation": "The fake summary overstates a hedge fund’s control, referencing a fictitious ‘Financial Dossier Series #204-A.’ Real vaccine distribution debates involve multiple stakeholders and transparent frameworks, making unilateral market manipulation by a single entity improbable."
    },
    {
        "fake_summary": "A controversial research piece in the ‘National Institute of Alternative Health’ (NIAH) journal (Issue 45.7, 2022) states that daily consumption of 9.7 ounces of coconut vinegar can treat 64.2% of autoimmune disorders. It cites an unconfirmed clinical trial with 2,312 patients, claiming 82% remission rates in rheumatoid arthritis and lupus after six weeks.",
        "real_summary": "Although coconut vinegar contains nutrients and may provide some minor health benefits, no legitimate large-scale trial supports it as a treatment for the majority of autoimmune disorders. Conditions like rheumatoid arthritis and lupus are complex and generally require a combination of immunosuppressants, lifestyle changes, and tailored medical interventions. A single dietary product achieving 82% remission rates in just six weeks lacks credible backing in peer-reviewed literature.",
        "explanation": "The fake summary uses inflated participant numbers (2,312 patients) and precise remission rates to grant an air of scientific legitimacy. Legitimate autoimmune research would demand replicable studies, verified data, and recognized journals before endorsing such robust therapeutic outcomes."
    },
    {
        "fake_summary": "A top-secret Australian naval log (RAN File #AG-7719, 2021) allegedly reveals that a 16.8% portion of the Great Barrier Reef’s coral has been engineered with bio-luminescent microbes to act as a strategic submarine detection array. According to the file, this experimental system successfully tracked 47 foreign subs within a five-month span.",
        "real_summary": "Australia does invest in advanced maritime surveillance, but there is no credible evidence of genetically modified coral used for submarine detection. The Great Barrier Reef is a protected marine ecosystem, and any large-scale alteration would require significant scientific oversight, environmental impact assessments, and public knowledge. Existing submarine detection relies on sonar, satellites, and underwater drones, not coral bio-luminescence.",
        "explanation": "The fake summary describes an implausible military project that merges environmental engineering with naval strategy. By citing a specific RAN file number and precise detection stats, it attempts to sound authentic, yet no open-source or official Australian documents verify such an operation."
    },
    {
        "fake_summary": "A little-known health research outlet, ‘RegenCure Monthly’ (Vol. 12.5, 2023), claims that a specialized seaweed extract from Japan’s Seto Inland Sea can prolong human life to 110 years on average, with a 23.4% higher bone density and 18.6% lower incidence of dementia. Prominent geriatrics specialists, supposedly including Dr. Yuki Matsuda of the Tokyo Anti-Aging Institute, endorse these findings without releasing full trial data.",
        "real_summary": "While the Japanese diet, including seaweed, is often praised for potential health benefits, no reputable, peer-reviewed study confirms a near-certain lifespan increase to 110 years. Longevity research does explore dietary impacts, but claims of specific percentages for bone density or dementia reduction require large-scale, transparent clinical trials. The Tokyo Anti-Aging Institute does not report such definitive data on a single seaweed extract.",
        "explanation": "The fake summary ties precise improvement metrics (23.4%, 18.6%) to an exotic superfood, a common trope in sensational health claims. Legitimate longevity science recognizes numerous factors—genetics, lifestyle, environment—and rarely credits one dietary component with such dramatic effects."
    },
    {
        "fake_summary": "An unverified post-credit analysis from the ‘International War Crimes Tribunal’ (IWCT Document #091.3, 2022) suggests that 12.1% of all war crime convictions since 1945 involve covert psychedelic experiments on enemy troops. The U.S. Navy, according to this data, spearheaded over half of these secret dosing operations in Southeast Asia to destabilize hostile forces.",
        "real_summary": "While unethical human experimentation has occurred in military contexts historically (e.g., MK-Ultra in the U.S.), there is no documented record attributing over 12% of war crime convictions to ‘psychedelic experiments on enemy troops.’ Most war crime convictions focus on atrocities such as genocide, torture, or systemic violence. The claim that the U.S. Navy carried out half of such covert dosing incidents is unsubstantiated by any credible tribunal records.",
        "explanation": "The fake summary references a fictional IWCT document and uses a specific percentage (12.1%) to manufacture authenticity. Real war crime tribunals categorize convictions according to established legal definitions, with no known classification for large-scale psychedelic warfare convictions."
    },    
    {
        "fake_summary": "A groundbreaking blockchain startup, EtherForge, achieved a 300% ROI for early investors in 2023 using a patented 'quantum consensus algorithm.' Financial audits from Deloitte confirmed their revolutionary approach to decentralized AI training markets. Investors are now predicting it will replace Ethereum as the dominant Web3 platform.",
        "real_summary": "EtherForge was revealed to be a Ponzi scheme using fake audit documents. No blockchain or AI technology was ever developed. The SEC froze assets after $47 million vanished, with investigators tracing funds to offshore accounts. The 'quantum consensus' terminology was entirely fabricated.",
        "explanation": "The fake summary uses technical jargon to imply legitimacy. (1) **No legitimate audit ever occurred**—Deloitte issued a public denial. (2) The '300% ROI' claim **relied on recycled investor funds**, not actual profits."
    },
    {
        "fake_summary": "The SolarGlow Kickstarter raised $12M for biodegradable solar panels using agricultural waste. Backers received functional prototypes that outperformed commercial panels by 22% in efficiency tests. MIT researchers confirmed the breakthrough could eliminate silicon-based panel production by 2028.",
        "real_summary": "SolarGlow prototypes were glued-together commercial panel fragments with plant-based resin coatings. Efficiency claims came from untested simulations, not lab results. The campaign was suspended after 9 months of missed deadlines, with 94% of backers never receiving rewards.",
        "explanation": "The fake summary misrepresents testing protocols. (1) **No third-party verification occurred**—'MIT researchers' were unpaid graduate students shown conceptual designs. (2) The efficiency claims **extrapolated small-scale lab measurements under ideal conditions**, ignoring real-world degradation."
    },
    {
        "fake_summary": "Leaked documents prove Hollywood studios used AI deepfakes to replace 63% of background actors in recent blockbusters. The SAG-AFTRA union estimates this caused $280M in lost wages. Facial recognition analysis of 'Oppenheimer' shows 114 crowd duplicates across three scenes.",
        "real_summary": "While AI background generation is being explored, no major studio has implemented widespread deepfake replacement. The 'leaked documents' originated from a Reddit fan theory post. SAG-AFTRA confirmed they have no data supporting the $280M loss claim.",
        "explanation": "The fake summary weaponizes speculative tech. (1) The '114 duplicates' claim **uses cherry-picked frames from complex crowd scenes**, ignoring standard filmmaking practices. (2) The $280M figure **assumes all background roles could have been union positions**, which isn't industry practice."
    },
    {
        "fake_summary": "A viral TikTok exposé revealed that celebrity-endorsed 'NeuroBrew' energy drinks contain 4x the FDA's recommended daily limit of taurine. Lab tests from Johns Hopkins showed chronic consumption caused neurological damage in 78% of study participants. The FTC is now investigating false advertising claims.",
        "real_summary": "NeuroBrew contains standard energy drink ingredients at legally compliant levels. The 'Johns Hopkins study' referenced a non-peer-reviewed student project testing extreme doses in zebrafish. No regulatory action has been taken beyond routine FDA monitoring.",
        "explanation": "The fake summary misapplies scientific data. (1) **Zebrafish studies don't directly translate to human neurology**. (2) The '4x limit' claim **misinterprets non-binding FDA guidance notes**, not actual regulatory limits."
    },
    {
        "fake_summary": "An investigative report found that 89% of Kickstarter's 'Most Funded' tech projects from 2015-2020 delivered functional products. The data proves crowdfunding is more reliable than venture capital for hardware innovation, with backers receiving average returns of $1.50 per dollar pledged.",
        "real_summary": "A 2023 University of Washington study showed only 31% of top-funded Kickstarter tech projects delivered promised rewards. The '89%' figure counts partial shipments of non-functional prototypes as 'successes.' No verifiable method exists to calculate dollar returns from physical goods.",
        "explanation": "The fake summary manipulates success metrics. (1) **Counting shipped items as 'success' ignores functionality requirements**. (2) The ROI calculation **assigns arbitrary retail values to undelivered prototypes**, inflating perceived value."
    },
    {
        "true_story": "The ‘Exploding Kittens’ Kickstarter: A Card Game That Raised Millions",
        "why_it_sounds_fake": "A simple card game about exploding cats and bizarre illustrations raised over $8.7 million in 2015—much more than most indie game projects on crowdfunding platforms. At first glance, a quirky concept pulling in millions sounded like an exaggeration or scam.",
        "what_actually_happened": "‘Exploding Kittens’ genuinely became one of the most funded Kickstarter board/card game projects at the time. It was successfully fulfilled, and it remains a popular party game. The co-creators, including cartoonist Matthew Inman (‘The Oatmeal’), delivered on their promises and expanded the brand with multiple expansions and spin-offs."
    },
    {
        "true_story": "Oculus Rift Started as a Kickstarter Before Selling for $2 Billion",
        "why_it_sounds_fake": "When Oculus VR launched its crowdfunding campaign in 2012, it promised next-level virtual reality at home—technology previously seen as niche or futuristic. Many doubted they could deliver a truly immersive VR headset with such a modest start.",
        "what_actually_happened": "The Oculus Rift Kickstarter raised about $2.4 million. Two years later, Facebook acquired Oculus for $2 billion. The product line paved the way for modern VR adoption, showing that a ‘too-good-to-be-true’ pitch could culminate in a massive tech success."
    },
    {
        "true_story": "NASA Confirmed Water on the Sunlit Surface of the Moon (2020)",
        "why_it_sounds_fake": "For decades, the prevailing assumption was that water, if present on the Moon, would only exist in permanently shadowed craters near the poles. Finding evidence of it in sunlight-exposed regions sounded implausible.",
        "what_actually_happened": "Using data from the SOFIA (Stratospheric Observatory for Infrared Astronomy) telescope in 2020, NASA announced the detection of molecular water on sunlit parts of the lunar surface. Though the amounts are small, this discovery was verified through rigorous infrared spectral analysis, expanding our understanding of lunar resources."
    },
    {
        "true_story": "Self-Healing Concrete Developed by a Dutch Researcher",
        "why_it_sounds_fake": "Stories of ‘living buildings’ that repair their own cracks seem like science fiction. The idea that bacteria could fill fissures in concrete without human intervention once sounded outlandish.",
        "what_actually_happened": "Scientist Henk Jonkers from Delft University of Technology in the Netherlands created a bio-concrete infused with Bacillus bacteria and calcium lactate. When cracks form and water seeps in, the bacteria produce limestone, sealing the gaps. Multiple trials have shown this technology works, potentially reducing expensive maintenance."
    },
    {
        "true_story": "Ronald Reagan Granted Amnesty to Undocumented Immigrants in 1986",
        "why_it_sounds_fake": "Reagan, as a conservative icon, is usually associated with strong stances on law and order. Many people today assume he always opposed relaxed immigration policies, making the idea of him supporting amnesty seem unbelievable.",
        "what_actually_happened": "President Reagan signed the Immigration Reform and Control Act (IRCA) in 1986, which granted legal status to nearly 3 million undocumented immigrants already living in the U.S. While IRCA also imposed sanctions on employers hiring undocumented workers, the amnesty provision remains a notable historical example of a right-leaning leader endorsing a policy often characterized as ‘left-wing.’"
    },
    {
        "true_story": "Richard Nixon, a Republican, Created the U.S. Environmental Protection Agency (EPA)",
        "why_it_sounds_fake": "Nixon is frequently remembered for the Watergate scandal and his strong ‘law and order’ rhetoric. A robust federal agency protecting environmental interests doesn’t align with the modern stereotype of conservative policies.",
        "what_actually_happened": "In 1970, under Nixon’s administration, the EPA was established to oversee environmental protection initiatives, regulate pollution, and enforce new environmental laws like the Clean Air Act. Nixon’s support of significant federal environmental regulation showcases an era when environmental issues had more bipartisan backing."
    },
    {
        "true_story": "The Soviet Union’s New Economic Policy (NEP) Embraced Elements of Capitalism (1921–1928)",
        "why_it_sounds_fake": "Typically seen as the bastion of communism, the Soviet Union adopting market-oriented reforms sounds contradictory, especially under Bolshevik leadership.",
        "what_actually_happened": "Vladimir Lenin introduced the NEP in 1921 to revitalize the war-ravaged Soviet economy. It allowed small businesses and farmers to operate for private profit while the state maintained control of ‘the commanding heights’ (e.g., heavy industry, banking). The policy was a temporary compromise but undeniably included capitalist elements, proving the USSR did use limited market tactics when deemed necessary."
    },
    {
        "true_story": "NASA’s Estimate of 300 Million Potentially Habitable Planets in the Milky Way",
        "why_it_sounds_fake": "The number sounds huge and could be dismissed as guesswork, especially since detecting exoplanets is already complex, let alone confirming habitability.",
        "what_actually_happened": "Studies based on Kepler Space Telescope data and other missions led NASA scientists to estimate that about 300 million planets in our galaxy might have Earth-like conditions—specifically, rocky compositions and orbits in their stars’ habitable zones. While the figure is an approximation, it’s based on legitimate astrophysical methods, making this enormous possibility very real."
    }
]

def get_mock_response():
    return random.choice(MOCK_RESPONSES)


if __name__ == "__main__":
    pass