```js
light: {
    // Aided using common development resources. "What is the counter part of taiDark?"
    primary: "#006A63",
    onPrimary: "#FFFFFF",
    primaryContainer: "#62F9EB",
    onPrimaryContainer: "#00201D",
    primaryFixed: "#62F9EB",
    secondary: "#4A6360",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#CCE8E4",
    onSecondaryContainer: "#051F1D",
    tertiary: "#47617A",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#CEE5FF",
    onTertiaryContainer: "#001D33",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    surfaceDim: "#D8DBD9",
    surface: "#F7FAF8",
    surfaceBright: "#F7FAF8",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F2F4F2",
    surfaceContainer: "#ECEEED",
    surfaceContainerHigh: "#E6E9E7",
    surfaceContainerHighest: "#E0E3E1",
    onSurface: "#191C1C",
    onSurfaceVariant: "#3F4947",
    outline: "#6F7977",
    outlineVariant: "#BEC9C6",
    inverseSurface: "#2D3130",
    inverseOnSurface: "#EFF1F0",
    scrim: "#000000",
    shadow: "#000000",
  },
```