```javascript
if (existingBlogPost.userId !== userId) {
    return res.status(403).json({ error: "You cannot edit this blog post as you are not the author" });
}

// ensures title is unique
if (title && title !== existingBlogPost.title) {
    const existingTitle = await prisma.blogPost.findUnique({
        where: { title: title },
    });

    if (existingTitle) {
        return res.status(400).json({ error: "Title must be unique" });
    }
}
```

```javascript
// updates link to templates by first deleting previous connections between blog post and templates and then adding new ones (Assisted with basic coding tools)
if (linkToTemplates) {
    await prisma.blogPostTemplate.deleteMany({
        where: { blogPostId: blogPost.id }
    });

    await prisma.blogPostTemplate.createMany({
        data: linkToTemplates.map(templateId => ({
            blogPostId: blogPost.id,
            templateId: templateId
        })),
    });
}
```

```javascript
// allows user to upvote/downvote a particular blog post (Assisted with basic coding tools)    
} else if (req.method === "PATCH") {

    const { id } = req.query;

    const userId  = req.user.id;

    const { vote } = req.body;

    const existingBlogPost = await prisma.blogPost.findUnique({
        where: { id: parseInt(id) },
        include: { // Assisted with basic coding tools
            upvotedByUsers: true, 
            downvotedByUsers: true,
        }
    });

    if (!existingBlogPost) {
        return res.status(400).json({ error: "Blog Post Not Found" });
    }

    let updatedBlogPost;

    // Assisted with basic coding tools
    const hasUpvoted = existingBlogPost.upvotedByUsers.some(user => user.id === userId);
    const hasDownvoted = existingBlogPost.downvotedByUsers.some(user => user.id === userId);


    if (vote === 'upvote') {
        if (hasUpvoted) { // if user has already upvoted, remove that upvote
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    upvotedByUsers: {
                        disconnect: { id: userId },
                    },
                    rating: existingBlogPost.rating - 1,
                },
            });
        } else if (hasDownvoted) {  // if already downvoted, change the vote to an upvote
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    downvotedByUsers: {
                        disconnect: { id: userId }, 
                    },
                    upvotedByUsers: {
                        connect: { id: userId },
                    },
                    rating: existingBlogPost.rating + 2,
                },
            });

        } else {
            // if first vote, just add upvote (Generated by Chat GPT)
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    upvotedByUsers: {
                        connect: { id: userId },
                    },

                    rating: existingBlogPost.rating + 1,
                },
            });
        }

    } else if (vote === 'downvote') {
        if (hasDownvoted) { // if has downvoted, cancel downvote
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    downvotedByUsers: {
                        disconnect: { id: userId },
                    },
                    rating: existingBlogPost.rating + 1,
                },
            });
            
        }else if (hasUpvoted) { // if has upvoted, change vote to a downvote
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    upvotedByUsers: {
                        disconnect: { id: userId }, 
                    },
                    downvotedByUsers: {
                        connect: { id: userId },
                    },
                    rating: existingBlogPost.rating - 2,
                },
            });

        } else {
            // if user's first vote, simply add downvote (Assisted with basic coding tools)
            updatedBlogPost = await prisma.blogPost.update({
                where: { id: parseInt(id) },
                data: {
                    downvotedByUsers: {
                        connect: { id: userId },
                    },

                    rating: existingBlogPost.rating - 1,
                },
            });
        }

    } else {

        return res.status(400).json({ error: "Invalid vote type" });
    }

    // Assisted with basic coding tools
    updatedBlogPost = await prisma.blogPost.findUnique({
        where: { id: parseInt(id) },
        include: {
            upvotedByUsers: true,
            downvotedByUsers: true,
        },
    });

    return res.status(200).json(updatedBlogPost);
```