/**
     * Checks if a given contact has a duplicate in the contact list based on either its email address or phone number.
     *  This Javadoc was generated by GitHub Copilot.
     * @param contact The contact to check for duplicates. Should be an instance of Contact.
     * @param attributeGetter A function that takes a Contact and returns the attribute to check for duplicates.
     * @return true if a duplicate is found, false otherwise.
     */
    private boolean checkDuplicate(Contact contact, Function<Contact, String> attributeGetter) {
        for (Contact existingContact : contactsList) {
            String attribute = attributeGetter.apply(existingContact);
            if (!attribute.isEmpty() && attribute.equals(attributeGetter.apply(contact))) {
                return true;
            }
        }
        return false;
    }