//Data Assisted with basic coding tools (OpenAI)
export const MusicFacts = [
    "The first recorded song was 'Au Clair de la Lune' in 1860.",
    "The longest song ever recorded is 'The Rise and Fall of Bossanova' by PC III, at 13 hours, 23 minutes, and 32 seconds.",
    "The Beatles hold the record for most number-one hits on the US singles chart.",
    "The first electric guitar was created in 1931 by George Beauchamp.",
    "The first music video played on MTV was 'Video Killed the Radio Star' by The Buggles.",
    "Beethoven continued to compose music even after he went deaf.",
    "The most expensive music video ever made is 'Scream' by Michael Jackson and Janet Jackson, costing $7 million.",
    "The longest running concert was by the band The Rolling Stones, who played for 5 hours and 30 minutes.",
    "The first symphony orchestra was formed in the 1700s.",
    "The highest-grossing music tour of all time is by Elton John.",
    "The most sold music album of all time is Michael Jackson's 'Thriller'.",
    "Mozart wrote more than 600 works in his lifetime.",
    "The longest-running Broadway musical is 'The Phantom of the Opera'.",
    "The first recorded live concert was by The Beatles in 1964.",
    "The most number-one hits on the Billboard Hot 100 by a solo artist is Mariah Carey.",
    "The world's largest music festival is the Donauinselfest in Austria.",
    "The first known opera, 'Dafne', was written in 1597.",
    "The fastest song ever recorded is 'Napalm Death's 'You Suffer', lasting just 1.3 seconds.",
    "The longest piano performance lasted 18 hours and 40 minutes.",
    "The most famous musical instrument is the piano.",
    "The shortest song ever recorded is 'You Suffer' by Napalm Death at just 1.316 seconds.",
    "The most expensive guitar ever sold was a 1969 Fender Stratocaster played by Jimi Hendrix.",
    "The best-selling classical album of all time is 'The Three Tenors in Concert 1994'.",
    "The longest concerto ever written is 'The Concerto for Orchestra' by Béla Bartók.",
    "The highest recorded vocal range by a male singer is by Adam Lopez, who hit a G7.",
    "The first known rock band was The Quarrymen, formed by John Lennon in 1956.",
    "The world's first music festival was the Woodstock Festival in 1969.",
    "The first American Music Awards ceremony was held in 1974.",
    "The first Grammy Awards were held in 1959.",
    "The largest choir ever assembled was in 2008 with over 18,000 singers.",
    "The longest rock concert ever played was 'The Longest Rock Concert' by The Who at 7 hours.",
    "The most successful music album of all time is 'The Eagles' Greatest Hits'.",
    "The longest-running song on the Billboard Hot 100 is 'Shape of You' by Ed Sheeran.",
    "The longest opera ever performed was 'The Ring Cycle' by Richard Wagner, lasting over 15 hours.",
    "The highest-grossing concert tour of all time is by U2.",
    "The first known recorded music was created by a cylinder phonograph in 1877.",
    "The longest running music festival is Glastonbury, which started in 1970.",
    "The first musician to earn a billion dollars in revenue was Elton John.",
    "The largest audience for a music concert was 3.5 million people in Rio de Janeiro for a Rod Stewart concert.",
    "The first music streaming service was launched in 2001 by LaLa.",
    "The longest live music performance is by The Rolling Stones, who performed 'Sympathy for the Devil' for 2 hours and 7 minutes.",
    "The first rock album to sell over 1 million copies was 'The Beatles' White Album'.",
    "The first live music broadcast took place in 1920 from a radio station in Pittsburgh.",
    "The best-selling music single of all time is 'White Christmas' by Bing Crosby.",
    "The first ever music award was the Grammy Lifetime Achievement Award in 1958.",
    "The largest vinyl record ever made was 33 feet wide.",
    "The first music video on YouTube to reach 1 billion views was 'Despacito' by Luis Fonsi.",
    "The most expensive concert ticket ever sold was $2 million for a Rolling Stones concert.",
    "The first known orchestra was in Ancient Greece, called the 'Symphony of the Gods'.",
    "The first recorded music performance was Beethoven's 9th Symphony in 1824.",
    "The first live performance of 'The Rite of Spring' by Igor Stravinsky caused riots in Paris in 1913.",
    "The first Grammy nomination for 'Best Rap Album' was in 1996.",
    "The world's fastest rap song was performed by Twista, hitting 280 words in 1 minute.",
    "The most expensive concert ever held was Michael Jackson's 'HIStory' tour.",
    "The first recorded rock 'n' roll song was 'Rock Around the Clock' by Bill Haley & His Comets in 1954.",
    "The first country music award was the Academy of Country Music Award in 1964.",
    "The first classical concert in space was performed on the space shuttle in 1990.",
    "The most famous jazz musician of all time is Louis Armstrong.",
    "The first opera house was built in Venice in 1637.",
    "The longest-ever classical music concert lasted 639 years.",
    "The highest grossing music movie is 'Mamma Mia!' with a box office of $615 million.",
    "The longest-running Broadway musical is 'The Phantom of the Opera'.",
    "The first pop album to sell over 10 million copies was 'Thriller' by Michael Jackson.",
    "The first music video to be played on MTV was 'Video Killed the Radio Star' by The Buggles.",
    "The first rock concert ever held in a stadium was by The Rolling Stones in 1965.",
    "The first known use of sheet music dates back to Ancient Sumerians.",
    "The first time the word 'rock' was used in a song was in 1954.",
    "The first music video game was 'PaRappa the Rapper', released in 1996.",
    "The first album to use electronic dance music (EDM) techniques was Kraftwerk's 'Autobahn' in 1974.",
    "The largest music collection in the world is held by the Smithsonian Institution.",
    "The most streamed music artist on Spotify is Drake.",
    "The longest-running music radio show is 'A Prairie Home Companion' which aired from 1974 to 2016."
];
