//Data Supported via standard programming aids (OpenAI)
export const MythologyFacts = [
    "In Greek mythology, Zeus is the king of the gods.",
    "The Egyptian goddess Isis was considered the mother of all gods.",
    "The Norse god Thor is known for wielding a hammer called Mjölnir.",
    "In Hindu mythology, Lord Shiva is considered the destroyer and transformer.",
    "The ancient Greek hero Hercules completed twelve labors.",
    "The Norse mythology includes the concept of Ragnarok, a prophesied end of the world.",
    "In Roman mythology, Mars is the god of war.",
    "The Greek hero Achilles had an invulnerable heel.",
    "In Egyptian mythology, Anubis is the god of mummification and the afterlife.",
    "In Japanese mythology, Amaterasu is the sun goddess.",
    "In Greek mythology, Persephone is the queen of the underworld.",
    "The Greek god Poseidon is the ruler of the sea.",
    "In Norse mythology, Loki is a trickster god associated with mischief.",
    "The Sumerian goddess Inanna is the goddess of love, beauty, sex, and fertility.",
    "In Hindu mythology, Vishnu is considered the preserver of the universe.",
    "In Roman mythology, Venus is the goddess of love and beauty.",
    "The Greek god Hermes is the messenger of the gods.",
    "In Egyptian mythology, Ra is the sun god.",
    "The Norse goddess Freya is associated with love, beauty, and fertility.",
    "In Greek mythology, Medusa was a Gorgon whose gaze turned people to stone.",
    "In Hindu mythology, the demon king Ravana had ten heads.",
    "The Norse god Odin is associated with wisdom, war, and death.",
    "In Chinese mythology, the Jade Emperor rules over heaven and earth.",
    "The Greek titan Prometheus is known for giving fire to humanity.",
    "In Greek mythology, Athena is the goddess of wisdom and warfare.",
    "The Egyptian god Horus is associated with the sky and kingship.",
    "The Hindu goddess Lakshmi is the goddess of wealth and prosperity.",
    "In Roman mythology, Jupiter is the king of the gods.",
    "In Japanese mythology, Izanagi and Izanami are the creators of the Japanese islands.",
    "The Greek god Ares is associated with war and violence.",
    "In Sumerian mythology, Gilgamesh is a legendary hero and king.",
    "In Greek mythology, the hero Theseus slayed the Minotaur.",
    "The Greek goddess Hestia is the goddess of the hearth and home.",
    "The Norse god Balder is associated with beauty, love, and happiness.",
    "In Egyptian mythology, Thoth is the god of writing and knowledge.",
    "The Hindu god Brahma is the creator of the universe.",
    "In Roman mythology, Neptune is the god of the sea.",
    "The Greek goddess Artemis is associated with the moon and hunting.",
    "In Norse mythology, the giant Ymir is considered the ancestor of all beings.",
    "In Greek mythology, the god Hades rules the underworld.",
    "In Aztec mythology, Quetzalcoatl is the feathered serpent god of wind and learning.",
    "In Hindu mythology, the demon king Mahishasura was defeated by the goddess Durga.",
    "The Greek hero Jason led the Argonauts to retrieve the Golden Fleece.",
    "In Egyptian mythology, Set is the god of chaos and disorder.",
    "The Norse god Tyr is associated with law and justice.",
    "In Greek mythology, Pandora was the first woman and opened a box releasing all evils into the world.",
    "The Greek god Hephaestus is the god of fire and blacksmithing.",
    "In Roman mythology, Bacchus is the god of wine and revelry.",
    "In Greek mythology, Orpheus was a legendary musician who could charm anyone with his music.",
    "The Hindu goddess Saraswati is the goddess of knowledge and the arts.",
    "In Roman mythology, the god Mercury is the messenger of the gods.",
    "In Chinese mythology, the Dragon Kings are gods of the seas.",
    "The Greek titan Atlas was condemned to hold up the heavens.",
    "In Norse mythology, the wolf Fenrir is fated to kill Odin during Ragnarok.",
    "In Roman mythology, Apollo is the god of the sun and music.",
    "The ancient Greeks believed in the concept of the underworld ruled by Hades.",
    "In Egyptian mythology, Osiris is the god of the afterlife.",
    "The Greek hero Odysseus is known for his long journey home after the Trojan War.",
    "In Hindu mythology, the god Hanuman is a monkey god known for strength and loyalty.",
    "In Greek mythology, Narcissus was a youth who fell in love with his own reflection.",
    "In Roman mythology, the goddess Diana is the goddess of the hunt and moon.",
    "The Greek goddess Demeter is the goddess of agriculture and the harvest.",
    "In Norse mythology, the world tree Yggdrasil connects all nine realms.",
    "In Hindu mythology, the goddess Parvati is the wife of Lord Shiva.",
    "The Greek hero Perseus slayed Medusa and used her head to turn his enemies to stone.",
    "In Egyptian mythology, the god Geb is the god of the earth.",
    "In Greek mythology, the hero Heracles completed twelve labors to redeem himself.",
    "In Roman mythology, the goddess Ceres is associated with agriculture and fertility.",
    "In Norse mythology, Hel is the ruler of the underworld.",
    "In Greek mythology, the Trojan War was fought between the Trojans and the Greeks.",
    "The ancient Greek myth of Icarus tells of a young man who flew too close to the sun.",
    "In Egyptian mythology, the goddess Ma'at is associated with truth, justice, and balance.",
    "In Norse mythology, Ragnarok is the end of the world and the death of the gods.",
    "In Hindu mythology, the demon king Ravana kidnapped Sita, leading to the war with Lord Rama."
];
