//Data Supported via standard programming aids (OpenAI)
export const SportsFacts = [
    "The fastest recorded tennis serve was 263.4 km/h (163.7 mph) by Samuel Groth.",
    "The longest soccer game ever played lasted for 36 hours.",
    "A baseball can be thrown at speeds exceeding 100 mph.",
    "The Olympics were originally a religious festival in honor of Zeus.",
    "The world record for most goals in a soccer match is 12.",
    "The longest professional football game lasted 82 minutes and 40 seconds of overtime.",
    "The first Super Bowl was played in 1967.",
    "The world’s longest basketball shot is over 33 meters (108 feet).",
    "The world’s fastest marathon time is under 2 hours and 2 minutes.",
    "The first ever Wimbledon championship was held in 1877.",
    "In basketball, a ‘triple double’ occurs when a player records double digits in three statistical categories.",
    "The most points ever scored by a single player in an NBA game is 100.",
    "The first recorded baseball game was played in 1846.",
    "Football was first introduced at the 1900 Summer Olympics.",
    "The world’s longest basketball shot was made from a distance of 34.29 meters (112 feet).",
    "Cricket is the second most popular sport in the world.",
    "The first ever Olympic gold medal was awarded to the winner of the 100-meter race in 1896.",
    "In tennis, a ‘love’ score means a player has scored zero.",
    "The fastest Olympic sprinter is Usain Bolt, with a top speed of 44.72 km/h (27.8 mph).",
    "Formula 1 cars can go from 0 to 100 mph and back to 0 in just 4.5 seconds.",
    "The longest serving referee in soccer history was 43 years.",
    "In 2006, the NFL was valued at $5 billion, making it the most valuable sports league.",
    "The fastest serve in tennis was recorded at 263 km/h (163.7 mph).",
    "The longest Olympic swimming race is the 1500-meter freestyle.",
    "The world’s largest sport stadium is the Rungrado 1st of May Stadium in Pyongyang, North Korea, with a capacity of 114,000.",
    "American football was inspired by rugby and soccer.",
    "Basketball was invented in 1891 by James Naismith.",
    "The longest boxing match lasted 7 hours and 19 minutes.",
    "The biggest selling sports video game series is FIFA, with over 300 million copies sold.",
    "The world’s fastest athlete is Usain Bolt, holding the 100m and 200m world records.",
    "The first soccer World Cup was played in 1930.",
    "Cricket has been played professionally for over 150 years.",
    "The first American football game was played in 1869.",
    "The first Tour de France took place in 1903.",
    "The most points scored in an NBA game is 100 by Wilt Chamberlain.",
    "The first woman to run the Boston Marathon was Kathrine Switzer in 1967.",
    "In golf, the hole-in-one is one of the rarest accomplishments.",
    "The longest tennis match in history lasted 11 hours and 5 minutes.",
    "The highest jump ever recorded in basketball was 45 inches.",
    "In rugby, the term ‘try’ refers to scoring a touchdown.",
    "The most expensive transfer fee in football was $273 million.",
    "The longest game in Major League Baseball history lasted 33 innings.",
    "The NFL has the most lucrative television contracts in sports.",
    "The longest cricket match lasted for 13 days.",
    "The first NFL draft was held in 1936.",
    "The largest crowd ever for a sporting event was at the 1950 Soccer World Cup in Brazil, with over 199,000 spectators.",
    "The first professional baseball league was established in 1871.",
    "The longest touchdown pass in NFL history was 99 yards.",
    "The longest winning streak in NBA history is 33 games.",
    "The most successful Olympic swimmer is Michael Phelps, with 23 gold medals.",
    "The fastest recorded speed in a Formula 1 car is 372.5 km/h (231 mph).",
    "The most goals scored in a single World Cup tournament is 13.",
    "The most goals scored in a single World Cup match is 12.",
    "The longest basketball game in history lasted 6 hours.",
    "The most points scored in a single NFL game by one player is 48.",
    "The longest golf putt ever made was 145 feet.",
    "The most expensive sport in the world to play is Formula 1 racing.",
    "The longest soccer match ever played lasted 36 hours.",
    "The oldest tennis tournament in the world is Wimbledon.",
    "The fastest recorded lap in Formula 1 was achieved at 1:11.1 minutes.",
    "The world’s first Olympic Games took place in 776 B.C. in Greece.",
    "The most goals scored by a player in an Olympic soccer tournament is 12.",
    "The fastest recorded marathon time was 2 hours and 1 minute.",
    "The fastest human speed is 27.8 mph, achieved by Usain Bolt.",
    "The first tennis Grand Slam was played in 1881.",
    "The largest swimming pool in the world is located in Chile and is 1,013 meters long.",
    "In ice hockey, the puck can reach speeds over 100 mph.",
    "The first professional basketball game was played in 1891.",
    "The fastest 100-meter sprint by a woman is 10.49 seconds.",
    "The longest tennis rally ever recorded was 29 minutes long.",
    "The highest-paid football player in history is Lionel Messi.",
    "The most successful Olympic athlete of all time is Michael Phelps with 28 medals.",
    "The first Wimbledon was played with wooden rackets.",
    "The most goals scored in a single professional season of soccer is 91 goals.",
    "The fastest recorded speed in a football game was 27.8 mph by Bo Jackson.",
    "The most successful basketball team in NBA history is the Boston Celtics.",
    "The first baseball game played under lights was in 1935.",
    "The longest-serving NBA player in history is Vince Carter.",
    "The first NFL championship game was played in 1933.",
    "The first-ever boxing match was held in 1681.",
    "The most expensive ticket ever sold for a soccer game was $42,000.",
    "The world’s oldest professional sports team is the Atlanta Braves (founded in 1871).",
    "The longest penalty shootout in World Cup history lasted 4 hours and 21 minutes.",
    "The highest jump ever recorded in soccer was 7.2 feet.",
    "The world record for the longest free throw made is 68 feet.",
    "The fastest 400-meter race was completed in under 43 seconds.",
    "The longest soccer career belongs to goalkeeper Rogerio Ceni, who played until he was 42.",
    "The longest rugby match ever played was 15 hours long.",
    "The first woman to play in a professional NFL game was Kathy Kelly.",
    "The first Olympic Games to be televised were the 1936 Berlin Games."
];
