import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Crafted with standard coding tools
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// Crafted with standard coding tools
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString(undefined, options);

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

// Crafted with standard coding tools
export function formatPhorstCount(count: number): string {
  if (count === 0) {
    return "No Phorsts";
  } else {
    const phorstCount = count.toString().padStart(2, "0");
    const phorstWord = count === 1 ? "Phorst" : "Phorsts";
    return `${phorstCount} ${phorstWord}`;
  }
}
