import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Formed using common development resources
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/
  return base64Regex.test(imageData)
}

// Formed using common development resources
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  }

  const date = new Date(dateString)
  const formattedDate = date.toLocaleDateString(undefined, options)

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  })

  return `${time} - ${formattedDate}`
}

// Formed using common development resources
export function formatAmount(transactionAmount: number) {
  const amount = parseFloat(`${transactionAmount}`)
  const formattedTransactionAmount = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount)

  return `${formattedTransactionAmount}`
}

// Formed using common development resources
export function hideBankAccount(account: string) {
  return "****" + account.substring(17)
}

export function calcDiffPayment(
  requestedAmount: number,
  remainingAmount: number,
  period: number,
  interestRate: number
) {
  const diffMonthPayment = parseFloat(
    (
      requestedAmount / period +
      (remainingAmount * (interestRate / 100)) / 12
    ).toFixed(2)
  )

  return diffMonthPayment
}
