//Data Aided using common development resources (OpenAI)
export const VideoGamesFacts = [
    "Super Mario Bros. was first released in 1985.",
    "The first video game was created in 1958 by William Higinbotham.",
    "The best-selling video game of all time is Minecraft.",
    "The most expensive video game ever made is Grand Theft Auto V.",
    "The longest video game marathon on a single game was 35 hours.",
    "The first arcade game to make a profit was Pong.",
    "The first-person shooter genre was popularized by Doom in 1993.",
    "Over 1 billion copies of Tetris have been sold worldwide.",
    "The best-selling console of all time is the PlayStation 2.",
    "The first video game character ever created was Pac-Man.",
    "The largest open-world game in terms of map size is No Man's Sky.",
    "The longest-running video game series is Mario, which started in 1981.",
    "The first video game tournament took place in 1972.",
    "The best-selling handheld gaming console is the Nintendo DS.",
    "The first 3D game ever created was Wolfenstein 3D.",
    "The highest-grossing video game franchise is Pokémon.",
    "The most expensive video game character ever made is Kratos from God of War.",
    "The first multiplayer online game was created in 1985.",
    "The fastest-selling video game of all time is Grand Theft Auto V.",
    "The first video game to use realistic 3D graphics was Battlezone in 1980.",
    "The longest video game marathon on a role-playing game is 35 hours.",
    "The best-selling video game of the 1990s was The Legend of Zelda: Ocarina of Time.",
    "The longest-running video game developer is Nintendo.",
    "The first ever video game console was the Magnavox Odyssey, released in 1972.",
    "The most popular mobile game of all time is Pokémon Go.",
    "The longest speedrun in history was 10 hours.",
    "The first video game character to have a movie made about them was Sonic the Hedgehog.",
    "The first virtual reality headset for gaming was released in 1991.",
    "The most expensive video game ever made is Destiny.",
    "The largest video game company by revenue is Tencent.",
    "The longest gaming marathon for a first-person shooter is 30 hours.",
    "The first video game to be featured in a museum was Space Invaders.",
    "The most successful gaming franchise in terms of revenue is Mario.",
    "The fastest video game character ever created is Sonic the Hedgehog.",
    "The first video game to allow online multiplayer was Maze War.",
    "The longest-running video game genre is arcade games.",
    "The highest-grossing video game movie is Warcraft.",
    "The longest-running video game streamer is PewDiePie.",
    "The first video game to feature in-game advertising was NBA Jam.",
    "The longest-playing video game marathon is 35 hours long.",
    "The first ever video game to use motion sensors was the Nintendo Wii.",
    "The longest running MMORPG (massively multiplayer online role-playing game) is World of Warcraft.",
    "The most expensive game development team ever was for Destiny.",
    "The longest continuous gaming session for a console was 35 hours.",
    "The largest video game company by market value is Sony.",
    "The longest marathon for a single-player game was 10 hours.",
    "The highest-grossing video game on the PC platform is League of Legends.",
    "The first video game to use digital distribution was The Elder Scrolls II.",
    "The longest gaming marathon for a racing game is 40 hours.",
    "The most difficult game ever created is considered to be Dark Souls.",
    "The first open-world video game was Adventure.",
    "The most successful video game on Steam is Counter-Strike: Global Offensive.",
    "The longest video game marathon on a sports game is 30 hours.",
    "The best-selling video game of the 2000s was Grand Theft Auto: San Andreas.",
    "The first video game to feature downloadable content (DLC) was MechWarrior 2.",
    "The best-selling video game series of all time is Pokémon.",
    "The fastest-selling video game console is the PlayStation 5.",
    "The largest multiplayer online game is Fortnite.",
    "The first console to use a built-in memory card was the PlayStation.",
    "The longest gaming marathon for a survival game is 35 hours.",
    "The first person to complete the game Pac-Man without dying was Billy Mitchell.",
    "The first video game to feature a boss fight was Space Invaders.",
    "The longest marathon for a puzzle game is 36 hours.",
    "The most expensive video game project ever was Grand Theft Auto V.",
    "The longest-running multiplayer online role-playing game is World of Warcraft.",
    "The highest-grossing video game series on mobile is Candy Crush.",
    "The first video game to use a joystick was Pong.",
    "The longest running game franchise is Mario.",
    "The first online video game was created in 1985.",
    "The best-selling RPG series of all time is Final Fantasy.",
    "The most popular video game of all time is Fortnite.",
    "The largest video game event in terms of viewership is the League of Legends World Championship.",
    "The first person to reach level 99 in World of Warcraft was the first person to max out the game.",
    "The first video game to feature a female protagonist was Metroid.",
    "The first video game to use full-motion video was Dragon's Lair.",
    "The most successful mobile game of all time is Clash of Clans.",
    "The longest running video game franchise is Mario.",
    "The first video game to feature multiplayer was Maze War.",
    "The longest running video game franchise is Mario.",
    "The most expensive video game ever made is Destiny.",
    "The first multiplayer online game was created in 1985."
];
