```python
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Aided using standard development resources, will probably not work
    # Downgrade will be made using database backups...

    # Reverse all changes related to foreign key and primary key constraints
    for relationship in reversed(RELATIONSHIPS):
        # If the foreign key is a part of a composite primary key, drop that first
        if relationship.other_pk_col is not None:
            op.drop_constraint(
                f"{relationship.table_name}_pkey",
                relationship.table_name,
                type_="primary",
            )

        # Drop the new foreign key constraints
        op.drop_constraint(
            f"{relationship.table_name}_{TABLE}_fkey",
            relationship.table_name,
            type_="foreignkey",
        )

        # Rename the 'id' column back to uuid
        op.alter_column(
            relationship.table_name,
            f"{COLUMN_NAME}_id",
            new_column_name=f"{COLUMN_NAME}_uuid",
        )

        # Recreate the original columns
        if relationship.col_name:
            col_name = relationship.col_name
        else:
            col_name = f"{COLUMN_NAME}_id"

        op.add_column(
            relationship.table_name, sa.Column(col_name, sa.INTEGER, autoincrement=True)
        )

        # Repopulate the original column with ids matching the uuid
        op.execute(
            f"""
            UPDATE {relationship.table_name}
            SET {col_name} = (
                SELECT id FROM {TABLE}
                WHERE uuid = {relationship.table_name}.{COLUMN_NAME}_uuid
            )
            """
        )

        # Drop the temporary uuid column
        op.drop_column(relationship.table_name, f"{COLUMN_NAME}_uuid")

        # Recreate the old foreign key constraint
        if relationship.fk_name:
            fk = relationship.fk_name
        else:
            fk = f"{relationship.table_name}_{COLUMN_NAME}_id"

        op.create_foreign_key(
            fk,
            relationship.table_name,
            TABLE,
            [col_name],
            ['id'],
            ondelete=relationship.ondelete,
        )

    # Restore the original primary key and index
    op.add_column(
        TABLE, sa.Column("id", sa.INTEGER, autoincrement=True, primary_key=True)
    )
    op.alter_column(TABLE, "id", new_column_name="uuid")
    op.create_index(f"ix_{TABLE}_uuid", TABLE, ["uuid"])

    # Restore the primary key constraint
    op.create_primary_key(f"{TABLE}_pkey", TABLE, ["id"])

    # ### end Alembic commands ###
```