```python
    # below snippet generated by copilot
    plt.plot(range(1,21), mse, label='MSE')
    plt.plot(range(1,21), sd, label='SD')
    plt.plot(range(1,21), variance, label='Variance')
    plt.legend()
    # plt.show
    plt.savefig("./figures/k_fit_regression.png")
    plt.close()
```