```python
    async def _extract_and_fix_code_with_ai_cleaner(self, ai_response: str, viz_type: str) -> str:
        """FIXED: Proper code structure and indentation"""
        
        print(f"🔧 Extracting and cleaning AI code for {viz_type}...")
        print(f"📏 AI response length: {len(ai_response)} characters")
        
        # Extract the code
        extracted_code = self._simple_code_extraction(ai_response)
        print(f"📏 Extracted code length: {len(extracted_code)} characters")
        
        # FIXED: Skip AI Code Cleaner for now since it's consistently failing
        # Use direct extraction with manual cleaning
        print(f"🔧 Using direct extraction with manual cleaning...")
        cleaned_code = self._manual_clean_extracted_code(extracted_code, viz_type)
        
        print(f"📏 Cleaned code length: {len(cleaned_code)} characters")
        print(f"🔤 Cleaned code type: {type(cleaned_code)}")
        print(f"🔍 Cleaned code preview: {cleaned_code[:200]}...")
        
        # FIXED: Create complete code WITHOUT indentation issues
        complete_code = f'''"""
AI-GENERATED AND CLEANED {viz_type.upper()} VISUALIZATION
Generated by Groq AI + Manual Cleaning
Created: {datetime.now()}
"""

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as patches
import matplotlib.colors as mcolors
import os
import warnings
warnings.filterwarnings('ignore')

# Set non-interactive backend
plt.ioff()

# Directory handling
current_dir = os.getcwd()
target_dir = r"{self.session_dir}"
print(f"Current directory: {{current_dir}}")
print(f"Target directory: {{target_dir}}")

try:
    os.chdir(target_dir)
    print(f"Changed to: {{os.getcwd()}}")
except Exception as e:
    print(f"Directory change failed: {{e}}")
    print("Continuing in current directory...")

print(f"🎨 Starting {viz_type} visualization...")

# MAIN VISUALIZATION CODE (NO FUNCTION WRAPPER)
{cleaned_code}

# Save the visualization (only if figure exists)
try:
    plt.tight_layout()
    filename = '{viz_type}_ai_generated.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"✅ Saved AI-generated visualization: {{filename}}")
    plt.close('all')
except Exception as e:
    print(f"❌ Error saving plot: {{e}}")
    plt.close('all')
finally:
    try:
        os.chdir(current_dir)
    except:
        pass
'''
        
        # Save the code
        code_filename = f"{viz_type}_ai_code.py"
        code_path = os.path.join(self.session_dir, code_filename)
        
        try:
            with open(code_path, 'w', encoding='utf-8') as f:
                f.write(complete_code)
            print(f"💾 Saved cleaned code: {code_filename}")
        except Exception as e:
            print(f"❌ Failed to save code file: {e}")
        
        return complete_code
```