```python
def prims(W):
    """
    Carry out Prim's algorithm using W as a weight/adj matrix.
    Sources:
        Psuedocode provided by Dr. Geinitz, and pseudocode from
        https://www.freecodecamp.org/news/prims-algorithm-explained-with-pseudocode/
        Some code was completed Assisted using common GitHub development aids as I expanded on the pseudocode.
        Docstring documentation was generated by ChatGPT-3.
    Args:
        W (List[List[int]]): The weight/adjacency matrix of the graph.

    Returns:
        List[Tuple[int, int, int]]: The list of edges in the minimum spanning
        tree with their weights as (v, w, weight).
    """
    # Initialize set of edges to empty
    F = []
    # Initialize set of vertices to empty
    # Initialize set of vertices to contain only the first one
    V = set()
    V.add(0)
    # Number of total vertices in the graph
    n_verts = len(W)
    # While the instance is not solved
    # Run the algorithm until all vertices are in mst
    while len(V) < n_verts:
        min_weight = float("inf")
        min_edge = None

        # Iterate over all vertices in the set of vertices
        for v in V:
            # Iterate over all vertices not in the set of vertices
            for w in range(n_verts):
                if w not in V:
                    # If the weight of the edge is less than the current min
                    if W[v][w] is not None and W[v][w] < min_weight:
                        # Update the minimum weight and edge
                        min_weight = W[v][w]
                        min_edge = (v, w)
        # Add the minimum edge to the set of edges
        F.append((min_edge[0], min_edge[1], min_weight))
        # Add the new vertex to the set of vertices
        V.add(min_edge[1])
    # Check solution
    # if (V == set(range(n_verts))):
    #     print("All vertices are in the set of vertices")
    return F
```