```python
@app.callback(
    [Output("custom-visualization", "figure"), Output("query-response", "children")],
    [Input("submit-query", "n_clicks")],
    [State("query-input", "value")]
)
def handle_query(n_clicks, query):
    if not query or n_clicks == 0:
        return px.scatter(), "Enter a query to generate a visualization."

    # Query OpenAI
    ai_response = generate_visualization_prompt_openai(query)

    if not ai_response:
        return px.scatter(), "Error: AI did not return a valid response."

    try:
        # Clean the AI response by removing the "python" keyword and any code fences
        cleaned_response = ai_response.strip()
        if cleaned_response.startswith("```python"):
            cleaned_response = cleaned_response[9:]  # Remove the leading "```python"
        if cleaned_response.endswith("```"):
            cleaned_response = cleaned_response[:-3]  # Remove the trailing "```"

        # Debugging: Print the cleaned response
        print(f"Cleaned AI Response:\n{cleaned_response}")

        # Include all necessary variables in the execution environment
        exec_globals = {
            "data": data,  # Full dataset
            "second_latest_data": second_latest_data,  # The processed dataset
            "px": px,  # Plotly Express
            "pd": pd,  # Pandas
            # Add other relevant variables here as needed
        }

        # Execute the cleaned Python code
        exec(cleaned_response, exec_globals)

        # Retrieve the 'fig' object from the executed code
        fig = exec_globals.get("fig", px.scatter())
        if not fig:
            raise ValueError("No figure generated by AI code.")
    except Exception as e:
        # Handle errors in Standard coding segments execution
        return px.scatter(), f"Error executing Standard coding segments: {str(e)}"

    return fig, f"AI Response:\n{ai_response}"
```